/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Guía de Aprendizaje 3 - Componentes del PC
 * @author LABORATORIO
 */
public class jfrmSupport extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmSupport() {
        initComponents();
        this.setLocationRelativeTo(null);//localizacion
        this.setTitle("Componentes del PC");//Titulo
        this.setResizable(false);//cambiar tamaño
    }
    
    private ImageIcon cargarImagenEscalada(String ruta) {
        return new ImageIcon(getClass().getResource(ruta));
    }
    
    private void mostrarComponente(String nombre, String rutaImagen, String concepto, String funcion) {
        jlblPiezas.setText(nombre);
        jlblNomPiezas.setText("");
        jlblNomPiezas.setIcon(cargarImagenEscalada(rutaImagen));
        jlblConcepto.setText("<html><div style='width:300px; padding:8px;'>" + concepto + "</div></html>");
        jlblFuncion.setText("<html><div style='width:300px; padding:8px;'>" + funcion + "</div></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPiezas = new javax.swing.JLabel();
        jlblNomPiezas = new javax.swing.JLabel();
        jlblTituloConcepto = new javax.swing.JLabel();
        jlblConcepto = new javax.swing.JLabel();
        jlblTituloFuncion = new javax.swing.JLabel();
        jlblFuncion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenuComponentes = new javax.swing.JMenu();
        itemMotherboard = new javax.swing.JMenuItem();
        itemProcesador = new javax.swing.JMenuItem();
        itemRam = new javax.swing.JMenuItem();
        itemHdd = new javax.swing.JMenuItem();
        itemSsd = new javax.swing.JMenuItem();
        itemFuente = new javax.swing.JMenuItem();
        itemGpu = new javax.swing.JMenuItem();
        itemRed = new javax.swing.JMenuItem();
        itemCooler = new javax.swing.JMenuItem();
        itemVentilador = new javax.swing.JMenuItem();
        itemSonido = new javax.swing.JMenuItem();
        itemCmos = new javax.swing.JMenuItem();
        itemSata = new javax.swing.JMenuItem();
        itemAlimentacion = new javax.swing.JMenuItem();
        itemBios = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();
        itemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 540));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jlblPiezas.setFont(new java.awt.Font("Segoe UI", 2, 28)); // NOI18N
        jlblPiezas.setForeground(new java.awt.Color(255, 255, 255));
        jlblPiezas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPiezas.setText("Componentes del PC Juan Dubón");

        jlblNomPiezas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNomPiezas.setPreferredSize(new java.awt.Dimension(480, 290));

        jlblTituloConcepto.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jlblTituloConcepto.setForeground(new java.awt.Color(255, 255, 255));
        jlblTituloConcepto.setText("Concepto");

        jlblConcepto.setBackground(new java.awt.Color(255, 255, 255));
        jlblConcepto.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jlblConcepto.setText("<html><div style='width:300px; padding:8px;'>Seleccione un componente en el menú para visualizar su información.</div></html>");
        jlblConcepto.setOpaque(true);
        jlblConcepto.setPreferredSize(new java.awt.Dimension(330, 110));

        jlblTituloFuncion.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jlblTituloFuncion.setForeground(new java.awt.Color(255, 255, 255));
        jlblTituloFuncion.setText("Función principal");

        jlblFuncion.setBackground(new java.awt.Color(255, 255, 255));
        jlblFuncion.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jlblFuncion.setText("<html><div style='width:300px; padding:8px;'>Aquí se mostrará la función principal del componente seleccionado.</div></html>");
        jlblFuncion.setOpaque(true);
        jlblFuncion.setPreferredSize(new java.awt.Dimension(330, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblPiezas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblNomPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTituloConcepto)
                                    .addComponent(jlblTituloFuncion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))))
                        .addGap(22, 22, 22)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblPiezas)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNomPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblTituloConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jlblTituloFuncion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenuArchivo.setText("Archivo");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemGuardar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuComponentes.setText("Componentes del PC");

        itemMotherboard.setText("Motherboard");
        itemMotherboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMotherboardActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemMotherboard);

        itemProcesador.setText("Procesador");
        itemProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProcesadorActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemProcesador);

        itemRam.setText("Memoria RAM");
        itemRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRamActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemRam);

        itemHdd.setText("Disco Duro (HDD)");
        itemHdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHddActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemHdd);

        itemSsd.setText("Unidad SSD");
        itemSsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSsdActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSsd);

        itemFuente.setText("Fuente de Poder");
        itemFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFuenteActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemFuente);

        itemGpu.setText("Tarjeta de Video (GPU)");
        itemGpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGpuActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemGpu);

        itemRed.setText("Tarjeta de Red");
        itemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRedActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemRed);

        itemCooler.setText("Cooler del Procesador");
        itemCooler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCoolerActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemCooler);

        itemVentilador.setText("Ventilador del Gabinete");
        itemVentilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentiladorActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemVentilador);

        itemSonido.setText("Tarjeta de Sonido");
        itemSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSonidoActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSonido);

        itemCmos.setText("Batería CMOS");
        itemCmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCmosActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemCmos);

        itemSata.setText("Cable SATA");
        itemSata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSataActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSata);

        itemAlimentacion.setText("Cable de Alimentación");
        itemAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlimentacionActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemAlimentacion);

        itemBios.setText("BIOS / UEFI");
        itemBios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBiosActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemBios);

        jMenuBar1.add(jMenuComponentes);

        jMenuAyuda.setText("Ayuda");

        itemAcerca.setText("Acerca del programa");
        itemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(itemAcerca);

        itemCreditos.setText("Créditos");
        itemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreditosActionPerformed(evt);
            }
        });
        jMenuAyuda.add(itemCreditos);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        int msg = JOptionPane.showConfirmDialog(null, "¿Desea salir del software?", "Salir", JOptionPane.YES_NO_OPTION);
        if (msg == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemMotherboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMotherboardActionPerformed
        mostrarComponente("Motherboard", "/imagenes/motherboard.png", "Es la placa principal donde se conectan los componentes de la computadora.", "Permite la comunicación y conexión entre el procesador, la memoria, el almacenamiento y los demás dispositivos.");
    }//GEN-LAST:event_itemMotherboardActionPerformed

    private void itemProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProcesadorActionPerformed
        mostrarComponente("Procesador", "/imagenes/cpu.png", "Es el circuito que interpreta y ejecuta las instrucciones de los programas.", "Procesa datos, realiza cálculos y coordina las operaciones de la computadora.");
    }//GEN-LAST:event_itemProcesadorActionPerformed

    private void itemRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRamActionPerformed
        mostrarComponente("Memoria RAM", "/imagenes/ram.png", "Es una memoria temporal que guarda datos mientras la computadora está encendida.", "Mantiene disponibles los programas y datos que se están utilizando para acceder a ellos rápidamente.");
    }//GEN-LAST:event_itemRamActionPerformed

    private void itemHddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHddActionPerformed
        mostrarComponente("Disco Duro (HDD)", "/imagenes/hdd.png", "Es un dispositivo de almacenamiento que utiliza discos magnéticos.", "Guarda de forma permanente el sistema operativo, programas y archivos del usuario.");
    }//GEN-LAST:event_itemHddActionPerformed

    private void itemSsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSsdActionPerformed
        mostrarComponente("Unidad SSD", "/imagenes/ssd.png", "Es una unidad de almacenamiento que utiliza memoria flash y no tiene piezas móviles.", "Almacena información permanentemente y permite iniciar y abrir archivos con mayor rapidez.");
    }//GEN-LAST:event_itemSsdActionPerformed

    private void itemFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuenteActionPerformed
        mostrarComponente("Fuente de Poder", "/imagenes/fuente.png", "Es el componente que transforma la corriente eléctrica para que pueda ser utilizada por la computadora.", "Distribuye energía eléctrica a la motherboard, discos, ventiladores y demás componentes.");
    }//GEN-LAST:event_itemFuenteActionPerformed

    private void itemGpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGpuActionPerformed
        mostrarComponente("Tarjeta de Video (GPU)", "/imagenes/gpu.png", "Es el componente especializado en procesar imágenes, videos y gráficos.", "Genera la señal visual que se muestra en el monitor y acelera tareas gráficas.");
    }//GEN-LAST:event_itemGpuActionPerformed

    private void itemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRedActionPerformed
        mostrarComponente("Tarjeta de Red", "/imagenes/red.png", "Es un dispositivo que permite conectar la computadora a una red.", "Envía y recibe datos para acceder a Internet o comunicarse con otros equipos.");
    }//GEN-LAST:event_itemRedActionPerformed

    private void itemCoolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCoolerActionPerformed
        mostrarComponente("Cooler del Procesador", "/imagenes/cooler.png", "Es el sistema de enfriamiento colocado sobre el procesador.", "Disipa el calor producido por el procesador para evitar el sobrecalentamiento.");
    }//GEN-LAST:event_itemCoolerActionPerformed

    private void itemVentiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentiladorActionPerformed
        mostrarComponente("Ventilador del Gabinete", "/imagenes/ventilador.png", "Es un ventilador instalado en el gabinete de la computadora.", "Introduce aire fresco y expulsa aire caliente para mantener una temperatura adecuada.");
    }//GEN-LAST:event_itemVentiladorActionPerformed

    private void itemSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSonidoActionPerformed
        mostrarComponente("Tarjeta de Sonido", "/imagenes/sonido.png", "Es el componente encargado de procesar las señales de audio.", "Permite reproducir y grabar sonido mediante bocinas, audífonos y micrófonos.");
    }//GEN-LAST:event_itemSonidoActionPerformed

    private void itemCmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCmosActionPerformed
        mostrarComponente("Batería CMOS", "/imagenes/cmos.png", "Es una pequeña batería ubicada en la motherboard.", "Mantiene la fecha, la hora y la configuración del BIOS cuando la computadora está apagada.");
    }//GEN-LAST:event_itemCmosActionPerformed

    private void itemSataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSataActionPerformed
        mostrarComponente("Cable SATA", "/imagenes/sata.png", "Es un cable utilizado para conectar unidades de almacenamiento a la motherboard.", "Transfiere datos entre la motherboard y dispositivos como discos HDD, SSD o unidades ópticas.");
    }//GEN-LAST:event_itemSataActionPerformed

    private void itemAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentacionActionPerformed
        mostrarComponente("Cable de Alimentación", "/imagenes/alimentacion.png", "Es un cable que transporta energía desde la fuente de poder hacia un componente.", "Suministra la electricidad necesaria para que los dispositivos internos puedan funcionar.");
    }//GEN-LAST:event_itemAlimentacionActionPerformed

    private void itemBiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBiosActionPerformed
        mostrarComponente("BIOS / UEFI", "/imagenes/bios.png", "Es el programa básico almacenado en un chip de la motherboard.", "Verifica e inicia el hardware y luego permite cargar el sistema operativo.");
    }//GEN-LAST:event_itemBiosActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Programa para conocer los componentes principales del PC.", "Acerca del programa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemAcercaActionPerformed

    private void itemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreditosActionPerformed
        JOptionPane.showMessageDialog(this, "Guía de Aprendizaje 3\nComputación Aplicada\nJuan Dubon - 11 IVC", "Créditos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemAlimentacion;
    private javax.swing.JMenuItem itemBios;
    private javax.swing.JMenuItem itemCmos;
    private javax.swing.JMenuItem itemCooler;
    private javax.swing.JMenuItem itemCreditos;
    private javax.swing.JMenuItem itemFuente;
    private javax.swing.JMenuItem itemGpu;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemHdd;
    private javax.swing.JMenuItem itemMotherboard;
    private javax.swing.JMenuItem itemProcesador;
    private javax.swing.JMenuItem itemRam;
    private javax.swing.JMenuItem itemRed;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSata;
    private javax.swing.JMenuItem itemSonido;
    private javax.swing.JMenuItem itemSsd;
    private javax.swing.JMenuItem itemVentilador;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComponentes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblConcepto;
    private javax.swing.JLabel jlblFuncion;
    private javax.swing.JLabel jlblNomPiezas;
    private javax.swing.JLabel jlblPiezas;
    private javax.swing.JLabel jlblTituloConcepto;
    private javax.swing.JLabel jlblTituloFuncion;
    // End of variables declaration//GEN-END:variables
}
